import type { Project } from "@/types/project";

const mockProjects: Project[] = [
  {
    id: "1",
    title: "Portföy Web",
    description: "React + TS + Tailwind + shadcn ile kişisel site.",
    year: 2024,
    tech: ["react", "ts", "tailwind"],
    demoUrl: "#",
    repoUrl: "#",
    stars: 12,
  },
  {
    id: "2",
    title: "Admin Panel Mini",
    description: "Cards, Table, Dialog, Toast ile UI denemeleri.",
    year: 2025,
    tech: ["react", "tailwind"],
    demoUrl: "#",
    repoUrl: "#",
    stars : 8,
  },
  {
    id: "3",
    title: "Node API",
    description: "Express + REST; frontend yok.",
    year: 2023,
    tech: ["node"],
    repoUrl: "#",
    demoUrl: "#",
    stars: 4,
  },
  {
    id: "4",
    title: "TS Utilities",
    description: "TypeScript yardımcı fonksiyon paketi.",
    year: 2024,
    tech: ["ts"],
    repoUrl: "#",
    stars: 5,
    demoUrl: "#",
  },
  {
    id: "5",
    title: "Blog Tema",
    description: "MDX destekli blog teması (React Router).",
    year: 2024,
    tech: ["react", "ts"],
    demoUrl: "#",
    repoUrl: "#",
    stars: 1,
  },
  {
    id: "6",
    title: "Chart Kit",
    description: "Recharts ile hazır grafik kartları (Line/Bar/Pie).",
    year: 2025,
    tech: ["ts", "tailwind"],
    repoUrl: "#",
    demoUrl: "#",
    stars: 1,
  },
  {
    id: "7",
    title: "Auth Starter",
    description: "JWT + Refresh token örneği (Node tabanlı).",
    year: 2023,
    tech: ["node", "ts"],
    repoUrl: "#",
    demoUrl: "#",
    stars: 2, 
  },
  {
    id: "8",
    title: "Landing Page",
    description: "Hero, features, pricing; tamamen Tailwind.",
    year: 2024,
    tech: ["tailwind"],
    demoUrl: "#",
    repoUrl: "#",
    stars: 5,
  },
  {
    id: "10",
    title: "Horror Game",
    description: "Korku temalı bir oyun.",
    year: 2024,
    tech: ["unity", "csharp"],
    demoUrl: "#",
    repoUrl: "#",
    stars: 2,
  },
   {
    id: "11",
    title: "Dont Leave Me ",
    description: "Korku temalı bir oyun.",
    year: 2024,
    tech: ["unity", "csharp"],
    demoUrl: "#",
    repoUrl: "#",
    stars: 3,
  },
   {
    id: "12",
    title: "Tarifler",
    description: "Hero, features, pricing; tamamen Tailwind.",
    year: 2024,
    tech: ["tailwind"],
    demoUrl: "#",
    repoUrl: "#",
    stars: 8,
  },
   {
    id: "13",
    title: "Kampanya",
    description: "Hero, features, pricing; tamamen Tailwind.",
    year: 2024,
    tech: ["tailwind"],
    demoUrl: "#",
    repoUrl: "#",
    stars: 7,
  },
];

export async function getProjects(): Promise<Project[]> {
  return new Promise((resolve) => setTimeout(() => resolve(mockProjects), 250));
}
